---
title: "Row Labels Needed to Spread"
Date: "2019-01-27"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = F, warning = F)
```

No explanation for this set of notes, just a few reminders when spreading and gathering.

```{r, echo = F, cache=T}
library(tidyverse)
cd_try <- data.frame(
  'b_partial' = c(1,2,3),
  'b_wo_partial' = c(4,5,6),
  'se_partial' = c(6,7,8),
  'se_wo_partial' = c(3,2,1)
)

cd_try

```

We want the columns to be "model," "result," and "value."

Here is my incorrect attempt.

```{r, cache=T}
cd_try <- cd_try %>%
  gather(b_partial, b_wo_partial, key = 'model', value = 'b1') 

cd_try

```

```{r, eval = F, cache=T}

cd_try <- cd_try %>%
  gather(se_partial, se_wo_partial, key = 'se_model', value = 'sd')

cd_try # not evaluated because it won't work
```

Instead, I need to gather everything in at the same time, split, and then spread.

```{r, echo = F, cache=T}
cd_try <- data.frame(
  'b_partial' = c(1,2,3),
  'b_wo_partial' = c(4,5,6),
  'se_partial' = c(6,7,8),
  'se_wo_partial' = c(3,2,1)
)

cd_try
```

Gather

```{r, cache=T}
cd_try <- cd_try %>%
  gather(b_partial, b_wo_partial, 
         se_partial, se_wo_partial,
         key = 'result_model', value = 'value') # gather everything

cd_try
```

Split

```{r, cache=T}
cd_try <- cd_try %>%
  separate(result_model, into = c('result', 'model'), sep = "_")

cd_try

```

Spread, BUT WHEN YOU SPREAD MAKE SURE TO INCLUDE ROW IDENTIFIERS.

```{r, cache=T}
cd_try <- cd_try %>%
  mutate(row_help = rep(1:6, 2))

cd_try <- cd_try %>%
  spread(result, value)

cd_try
```


Bo$^2$m =)
